apiVersion: apps/v1
kind: Deployment
metadata:
  name: tevra-cars-deployment
  labels:
    app: tevra-cars
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tevra-cars
  template:
    metadata:
      labels:
        app: tevra-cars
    spec:
      containers:
      - name: tevra-cars
        image: tevra-cars:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
